---
- hosts: all
  become: yes

  tasks:
    - name: Update EC2
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install pip
      apt:
        name: python3-pip
        update_cache: yes
        cache_valid_time: 3600
        state: present

    - name: Install Flask
      pip:
        name: flask
        state: present

    - name: Install bs4
      pip:
        name: bs4
        state: present

    - name: Install selenium
      pip:
        name: selenium
        state: present

    - name: Install gunicorn
      pip:
        name: gunicorn
        state: present

    - name: Download and install Chrome
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome-stable.deb
      register: google_chrome_deb

    - name: Install Chrome
      apt:
        deb: "{{ google_chrome_deb.dest }}"
        state: present

    - name: Create portfolio directory
      file:
        path: /home/ubuntu/best-deals
        state: directory

    - name: Pull repository in user home directory
      git:
        repo: https://github.com/akash66sheoran/best-deals-scraper.git
        dest: "/home/ubuntu/best-deals"

    - name: Deploy application
      shell: gunicorn -b 0.0.0.0:5000 app:app